# Generated by Django 3.2.7 on 2022-01-05 17:46

from django.db import migrations, models
import magiclink.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLink',
            fields=[
                ('id', models.CharField(default=magiclink.models.get_uuid, max_length=36, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=128)),
                ('token', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_expired', models.DateTimeField()),
            ],
        ),
    ]
