# Generated by Django 3.2.7 on 2022-01-09 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import scribbli.models.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name_slugify', models.CharField(blank=True, max_length=80)),
                ('name_slug', models.CharField(blank=True, max_length=84, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='universe.region')),
            ],
            options={
                'abstract': False,
            },
            bases=(scribbli.models.mixins.ContentTypeMixin, models.Model),
        ),
    ]
